### PR TITLE
Add background image

### LINKED ISSUE #2: Add background image
In order to make the VS AI experience match the PVP Cuttle experience, we should update the GameView to use the same background image that the PVP application does: https://github.com/cuttle-cards/cuttle/blob/main/public/img/game/board-background.svg

This should use the same or similar CSS that the PVP app's GameView does: setting the image as an element's `background-image` in CSS using `background-size: cover` and `background-position: center`. See the [PR](https://github.com/cuttle-cards/cuttle/pull/128/files) that added this file to the pvp app for comparison.

### PR DESCRIPTION
**Pull request by JonasThers**
- Resolves #2 
Screenshot 2023-10-19 at 23 01 55

### CODE REVIEW

**Comment by JonasThers** [comment]
@itsalaidbacklife So this had some different overlaying issues (see first image), so I've been making some adjustments, so everything fits better.

Now the issue is that when I click "Toggle deck", the added cards stretch the background image (two last images). Any suggestions on how to get around this?
Screenshot 2023-10-19 at 21 30 48
Screenshot 2023-10-19 at 21 44 20
Screenshot 2023-10-19 at 21 44 34

**Comment by itsalaidbacklife** [comment]
@JonasThers honestly I think we can remove that whole feature. The point of showing the deck was largely to be able to cheat which was mainly helpful for local development. 

Perhaps the right move is to wrap the button and the deck in an `ng-if=NODE_ENV==='development'` that hides them when in production, that way they can still be used for development. If we wanted to support the feature for real I'd say the move would be to tuck them into a dialog so they don't affect the overall layout. I'm okay to take it out and just keep it around for local debugging though.

**Comment by JonasThers** [comment]
Will wrap it up in the check for `NODE_ENV` check, thanks for your response!

**Review by itsalaidbacklife — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
